### ISSUE TITLE
SpringBoot integration problem

### ISSUE THREAD

**Issue by dmarko484** [javaplugs/spring-jsf#1]
I'm trying to integrate it with Spring Boot 1.3M5  but I'm getting error as below when running 'gradle bootRun'. It seems to be conflict with servlet-api version. Any idea how can I solve this?

java.lang.NoSuchMethodError: javax.servlet.ServletContext.addFilter(Ljava/lang/String;Ljavax/servlet/Filter;)Ljavax/servlet/FilterRegistration$Dynamic;

**Comment by rumatoest** [comment]
I'm not really sure that JSF compatible with spring boot.

Can you setup your JSF without my artifact? 
Can you access any spring bean from JSF pages using EL?

**Comment by cenobyte321** [comment]
You need to add this dependency:
http://mvnrepository.com/artifact/javax.servlet/servlet-api/2.5

Update: Disregard that, it will create a conflict with the embedded Apache Tomcat.
