### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by hcmm** [javaplugs/spring-jsf#2]
Can anyone help me with this issue ?

`"java.lang.NullPointerException
    at com.github.javaplugs.jsf.ViewScope.get(ViewScope.java:58)`

**Comment by rumatoest** [comment]
Not enough information to reproduce this bug.
It will be very good if you will reproduce this bug on test project and post here reference.

**Comment by hcmm** [comment]
My problem is in a service to upload. As the spring controllers the context are singletons, I looked for a session scope solution . However, when the user is using 2 or more tabs there is the problem of overwriting the file upload list. The idea is to use the scope view that exists in the jsf for each tab has its list. I'm having this null pointer. Can you help me? The service is FileUploadService and the controller is FileController. Follow the link: [https://github.com/hcmm/springJavaUpload](https://github.com/hcmm/springJavaUpload)

**Comment by rumatoest** [comment]
Could you debug your project and tell were exact null occures at 58 line in ViewScope?

**Comment by rumatoest** [comment]
Looks like this is project configuration issue, not spring-jsf problem.

**Comment by hcmm** [comment]
Yeah! The error continue same line:
`Caused by: java.lang.NullPointerException
    at com.github.javaplugs.jsf.ViewScope.get(ViewScope.java:58)`

Could you provide an example project with spring-jsf working?

**Comment by rumatoest** [comment]
This is an open source code. 
It works in this way. If you find an error - you should investigate it, fix it and them submit pull request here.
