### ISSUE TITLE
@PreDestroy method on View Scoped beans are never called

### ISSUE THREAD

**Issue by MaikelNait** [javaplugs/spring-jsf#4]
It seems, when using a custom Spring scope to handle the JSF View Scoped beans, as in your project, their @PreDestroy method is never called, and therefore we may have a memory leak here.

Even more, the ViewScope.valueUnbound() or ViewScope.remove(), or even the ViewScopeViewMapListener.doCallback() are never called.

How to verify that the ViewScoped beans are really removed from the scope when navigating to a new View ???

**Comment by rumatoest** [comment]
Will check and response later

**Comment by giquieu** [comment]
I noticed that the Beans are removed to change pages or to expire the session. Is that correct?

**Comment by rumatoest** [comment]
@giquieu Do you know how JSF view beans scope should work?

**Comment by giquieu** [comment]
@rumatoest I do not know much for sure ... I'm learning ...
I just noticed in my project that annotating a Bean with @Scope ("view") @PreDestroy is only called when I make a redirect or the session expires.
And I do not know if this is normal.
Would you have any easy-to-understand material on the JSF Bean lifecycle?

**Comment by rumatoest** [comment]
@giquieu 
I'm not providing any manual or tutorial for JSF. Before using my plugin you must know what JSF is and how does it work.

BTW @MaikelNait We've done some tests. And looks like this methods are called eventually, but it depends on particular JSF implementation. They are actually not called when you are expecting them to be called :)
